sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 19805601056Bkj@@

  redis:
    host: localhost
    port: 6379
    database: 0
  wx:
    appid: wx13948869c06193ff
    secret: 7e2d64209867df944fc7063cc8853891
